version: '2'

services:
  kitchen:
    build:
      context: .
    volumes:
    - ..:/usr/kitchen
    - ../.ssh:/root/.ssh:ro
    - ../kitchen/.envrc.example:/usr/kitchen/.envrc
    - ../.tmp/vault/config.json:/tmp/vault/config.json:rw
    - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file: 
    - .env 
    - .env.default
    environment: 
    - DOCKER_MACHINE_IP=$DOCKER_MACHINE_IP
    - VAULT_CONFIG_PATH=/tmp/vault/config.json # there are will be is located the config with a vault root token   
    labels: 
    - env=development
    - sandbox=true
    tty: true