# how to use:
#   DOCKER_MACHINE_IP=54.197.20.233 CONSUL_BACKEND_ADDR=consul:8500 docker-compose -f common.yml up -d

version: '2'

services:
  registrator:
    image: gliderlabs/registrator
    networks:
    - consul
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro 
    command: -resync 5 -ttl 30 -ttl-refresh 25 -ip $DOCKER_MACHINE_IP consul://agent:8500
 
networks:
  consul:
    external:
      name: consul_default
      