version: '2'

services:
  consul:
    image: $CONSUL_IMAGE
    restart: always
    container_name: consul
    ports:
    - '8300:8300'
    - '8301:8301'
    - '8301:8301/udp'
    - '8302:8302'
    - '8302:8302/udp'
    - '8400:8400'
    - '8500:8500'
    - '8600:8600'
    environment:
    - CONSUL_LOCAL_CONFIG=$CONSUL_SERVER_CONFIG
    - SERVICE_IGNORE=true
    volumes:
    - 'consul_data:/var/consul'
    command: agent -server -advertise=$DOCKER_MACHINE_IP -bind=0.0.0.0 -client=0.0.0.0 -ui -data-dir /var/consul -config-dir /consul/config $CONSUL_SERVER_OPTS

volumes:
  consul_data:
    driver: local
