version: '2'

services:
  server:
    image: consul:v0.6.4
    hostname: server
    ports:
    - '53:53/udp' # The DNS server
    - '8300:8300' # Server RPC address
    - '8301:8301' # The Serf LAN port
    - '8301:8301/udp' # The Serf LAN port
    - '8302:8302' # The Serf WAN port
    - '8302:8302/udp' # The Serf WAN port
    - '8400:8400' # The CLI RPC endpoint
    - '8500:8500' # The HTTP API
    - '8600:8600' # The DNS server
    - '8600:8600/udp' # The DNS server
    command: agent -server -bootstrap-expect 2 -bind=0.0.0.0 -client=0.0.0.0 -data-dir /tmp/consul -ui-dir /ui
    
  server01:
    image: consul:v0.6.4
    hostname: server01
    links:
    - server
    ports:
    - 53/udp
    - 8300
    - 8301
    - 8301/udp
    - 8302
    - 8302/udp
    - 8400
    - 8500
    - 8600
    - 8600/udp
    command: agent -server -bind=0.0.0.0 -client=0.0.0.0 -data-dir /tmp/consul -ui-dir /ui -node server01 -rejoin -retry-join=server