version: '2'

services:
  agent:
    image: $CONSUL_IMAGE
    ports:
    - '53:53/udp'
    - '8300:8300'
    - '8301:8301'
    - '8301:8301/udp'
    - '8302:8302'
    - '8302:8302/udp'
    - '8400:8400'
    - '8500:8500'
    - '8600:8600'
    environment:
    - SERVICE_IGNORE=true
    command: agent -advertise=$DOCKER_MACHINE_IP -bind=0.0.0.0 -client=0.0.0.0 -rejoin -retry-join=$CONSUL_SERVER_LEADER $CONSUL_AGENT_OPTS
    