version: '2'

services:
  agent:
    image: $CONSUL_IMAGE
    container_name: agent
    ports:
    - '8300:8300' # Server RPC address
    - '8301:8301' # The Serf LAN port
    - '8301:8301/udp' # The Serf LAN port
    - '8302:8302' # The Serf WAN port
    - '8302:8302/udp' # The Serf WAN port
    - '8400:8400' # The CLI RPC endpoint
    - '8500:8500' # The HTTP API
    - '8600:8600' # The DNS server 
    environment:
    - SERVICE_IGNORE=true
    - CONSUL_LOCAL_CONFIG=$CONSUL_AGENT_CONFIG
    command: agent -advertise=$DOCKER_MACHINE_IP -bind=0.0.0.0 -client=0.0.0.0 -rejoin -retry-join=$CONSUL_SERVER_LEADER $CONSUL_AGENT_OPTS
    