# version: '2'

# services:
consul:
  image: consul:v0.6.4
  hostname: consul
  ports:
  - '8300:8300'
  - '8301:8301'
  - '8302:8302'
  - '8400:8400'
  - '8500:8500'
  - '8600:8600'
  environment:
  - FOO=bar
  volumes:
  - /tmp/consul.d:/etc/consul.d
  command: agent -server -bootstrap-expect 3 -bind=0.0.0.0 -client=0.0.0.0 -data-dir /tmp/consul -config-dir /etc/consul.d -ui-dir /ui

agent:
  # depends_on:
  # - consul
  image: consul:v0.6.4
  links:
  - consul
  ports:
  - 8400
  environment:
  - FOO=bar
  command: agent -bind=0.0.0.0 -client=0.0.0.0 -rejoin -retry-join=consul -node agent-01