# http -v DELETE $CONSUL_ADDR/v1/kv/ recurse==

version: '2'

services:
  vault:
    image: cgswong/vault:0.5.2
    ports:
    - '8200:8200'
    volumes:
    - ../vault/config/dev.hcl:/etc/vault.hcl:ro
    command: server -config /etc/vault.hcl