# http -v DELETE $CONSUL_ADDR/v1/kv/ recurse==

version: '2'

services:
  vault:
    image: $VAULT_IMAGE
    ports:
    - '8200:8200'
    environment: 
    - VAULT_BACKEND=consul
    - VAULT_ADVERTISE_ADDR=$VAULT_ADVERTISE_ADDR
    - CONSUL_BACKEND_ADDR=$CONSUL_BACKEND_ADDR
    command: server -config /etc/vault.hcl