#! /bin/bash

##### Global Variables
CONSUL_CLUSTER_SIZE=${CONSUL_CLUSTER_SIZE:-3}
CONSUL_AGENTS=${CONSUL_AGENTS:-1}

export SHELL=${SHELL:-"$(which zsh)"}
export DOCKER_MACHINE_IP=
export CONSUL_IMAGE=vymarkov/consul:0.6.4
export CONSUL_SERVER_OPTS=
export CONSUL_AGENT_OPTS=
export CONSUL_SERVER_PRIMARY=
export BOOTSTRAP_EXPECT=$CONSUL_CLUSTER_SIZE

export CONSUL_BACKEND_ADDR=
export VAULT_ADVERTISE_ADDR=